[package]
name = "os"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = "0.5"

[profile]
dev = { panic = "abort" }
release = { panic = "abort" }

[[bin]]
name = "os"
test = false
bench = false